---
- name: Ensure that BIND is not installed in order to avoid conflicts with dnsmasq
  apt:
    package: bind9
    state: absent
  
- name: Install dnsmasq
  apt:
    package: dnsmasq

- name: disable the resolved service in order to avoid conflicts with dnsmasq
  command: sudo systemctl disable systemd-resolved
  
- name: Stoping the resolved service in order to avoid conflicts with dnsmasq
  command: sudo systemctl stop systemd-resolved
  
- name: removing the resolved service Files in order to avoid conflicts with dnsmasq
  command: rm /etc/resolv.conf
 
- name: Set nameserver 1.1.1.1
  command: echo "nameserver 8.8.8.8" > /etc/resolv.conf

- name: Generate the dnsmasq configuration file
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: Restart dnsmasq

- name: Create the dnsmasq systemd drop-in configuration directory
  file:
    path: "{{ dnsmasq_systemd_service_path }}"
    state: directory

- name: Generate the dnsmasq systemd drop-in service file
  template:
    src: dnsmasq.service.j2
    dest: "{{ dnsmasq_systemd_service_path }}/10-restart-failure.conf"
    mode: 0644

- name: Enable the dnsmasq service
  systemd:
    daemon_reload: yes
    name: dnsmasq.service
    enabled: yes
    state: restarted
